apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dugeun.fullname" . }}-mem-hpa
  labels:
    app: {{ include "dugeun.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "dugeun.fullname" . }}
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80  # v2beta2의 metrics 대신 사용
