apiVersion: v1
kind: Service
metadata:
  name: {{ include "dugeun.fullname" . }}
  labels:
    app: {{ include "dugeun.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ index .Values.service.ports 0 "port" }}
      targetPort: {{ index .Values.service.ports 0 "targetPort" }}
      nodePort: {{ index .Values.service.ports 0 "nodePort" }}
  selector:
    app: {{ include "dugeun.name" . }}
