replicaCount: 1

image:
  repository: seol11796/dugeun
  pullPolicy: IfNotPresent


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  ports:
  - nodePort: 32751
    port: 8080
    targetPort: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []

  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
